spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/finance_control}
    username: ${DATABASE_USERNAME:finance_control}
    password: ${DATABASE_PASSWORD:1234567}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
