CREATE TABLE "tb_categories" (
    "id" integer PRIMARY KEY,
    "user_id" integer,
    "name" varchar(250),
    "description" text,
    "is_active" BOOLEAN,
    "created_at" timestamp,
    "deleted_at" timestamp
);

ALTER TABLE tb_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE tb_categories ADD FOREIGN KEY ("user_id") REFERENCES "tb_users" ("id");
