CREATE TABLE "tb_expenses" (
    "id" integer PRIMARY KEY,
    "user_id" integer NOT NULL,
    "category_id" integer NOT NULL,
    "amount" integer NOT NULL,
    "payment_method" VARCHAR(100) NOT NULL,
    "description" text,
    "created_at" timestamp,
    "deleted_at" timestamp
);

ALTER TABLE tb_expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE tb_expenses ADD FOREIGN KEY ("user_id") REFERENCES "tb_users" ("id");
ALTER TABLE tb_expenses ADD FOREIGN KEY ("category_id") REFERENCES "tb_categories" ("id");
